//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ratep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card_work
    {
        public int PAUID { get; set; }
        public Nullable<int> CodePost { get; set; }
        public int CodeOperation { get; set; }
        public int OperatonOrder { get; set; }
        public int ElapsedTime { get; set; }
    
        public virtual Operation Operation { get; set; }
        public virtual Part_assembly_unit Part_assembly_unit { get; set; }
        public virtual Post Post { get; set; }
    }
}
