//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ratep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FA_Employees
    {
        public int EmployeeID { get; set; }
        public int AccountID { get; set; }
        public int CodePost { get; set; }
        public Nullable<int> ManufactoryID { get; set; }
    }
}
