//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ratep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPosition
    {
        public int PosID { get; set; }
        public int OrderID { get; set; }
        public int PAUID { get; set; }
        public int Ammount { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Part_assembly_unit Part_assembly_unit { get; set; }
    }
}
